CC ?= cc
EXTRA_CFLAGS ?= -pipe -Os -Wall
COMPFLAGS = $(EXTRA_CFLAGS) -D_BSD_SOURCE -D_GNU_SOURCE -D__KERNEL_STRICT_NAMES

COMMONDEFS = $(COMPFLAGS) -D_BSD_SOURCE -D_GNU_SOURCE

LDFLAGS ?= -s

DESTDIR ?=
PREFIX ?= /usr
BINDIR ?= $(PREFIX)/bin
DATADIR ?= $(PREFIX)/share
MANDIR ?= $(DATADIR)/man
FONTDIR ?= $(DATADIR)/fonts
DOCDIR ?= $(DATADIR)/doc

DPMS=-DDPMSExtension
SCREENSAVER=-DSCREENSAVER
MIT-SHM=-DMITSHM
RENDER=-DRENDER
SHAPE=-DSHAPE
SYNC=-DXSYNC
TOG-CUP=-DTOGCUP
XCMISC=-DXCMISC
XTEST=-DXTEST
XTRAP=-DXTRAP
XV=-DXV
RANDR=-DRANDR
XRECORD=-DXRECORD
XDMCP=-DXDMCP
FONTCACHE=-DFONTCACHE
SERVER_LOCK=-DSERVER_LOCK
SMART_SCHEDULE=-DSMART_SCHEDULE
XDMCP=-DXDMCP
PANORAMIX=-DPANORAMIX
X_LOCALE=-DX_LOCALE
PIXPRIV=-DPIXPRIV
XF86BIGFONT=-DXF86BIGFONT
BIGREQS=-DDBIGREQS

COMMONDEFS=$(COMPFLAGS) \
-DNOERROR \
-Dlinux \
-D_POSIX_SOURCE \
-D_BSD_SOURCE \
-DTOSHIBA_SMM \
-D_SVID_SOURCE \
-D_GNU_SOURCE \
-DKDRIVESERVER \
-DGCCUSESGAS \
-DDDXOSINIT \
-DNDEBUG \
-DNARROWPROTO \
-DFUNCPROTO=15 \
-DCOMPILEDDEFAULTFONTPATH=\"$(FONTDIR)/misc/,$(FONTDIR)/truetype/,$(FONTDIR)/100dpi/,$(FONTDIR)/75dpi/,$(FONTDIR)/cyrillic/\" \
-D_POSIX_C_SOURCE=2 \
$(FONTCACHE) \
$(XTEST) \
$(DPMS) \
$(SYNC) \
$(PANORAMIX) \
$(SHAPE) \
$(TOG-CUP) \
$(MIT-SHM) \
$(RENDER) \
$(SCREENSAVER) \
$(SERVER_LOCK) \
$(SMART_SCHEDULE) \
$(XCMISC) \
$(XDMCP) \
$(XTRAP) \
$(XV) \
$(RANDR) \
$(XRECORD) \
$(PIXPRIV) \
$(X_LOCALE) \
$(XF86BIGFONT) \
$(BIGREQS)